---
version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  open-pull-requests-limit: 0
  schedule:
    interval: monthly
- package-ecosystem: npm
  directory: "/"
  open-pull-requests-limit: 0
  schedule:
    interval: monthly
- package-ecosystem: composer
  directory: "/"
  open-pull-requests-limit: 0
  schedule:
    interval: monthly
- package-ecosystem: bundler
  directory: "/"
  open-pull-requests-limit: 0
  schedule:
    interval: monthly
