require:
  - rubocop-capybara
  - rubocop-graphql
  # - rubocop-i18n
  - rubocop-minitest
  - rubocop-performance
  # - rubocop-rails
  # - rubocop-rake
  - rubocop-rspec
  # - rubocop-rspec_rails
  - rubocop-thread_safety
AllCops:
  EnabledByDefault: true
Style/DisableCopsWithinSourceCodeDirective:
  Enabled: false
Bundler/GemComment:
  Enabled: false
Layout/LineLength:
  Enabled: false
Layout/RedundantLineBreak:
  Enabled: false
Lint/ConstantResolution:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Naming/InclusiveLanguage:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/Copyright:
  Enabled: false
  AutocorrectNotice: 'Copyright (c) 2024 by name all rights reserved.'
Style/Documentation:
  Enabled: false
Style/DocumentationMethod:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/ImplicitRuntimeError:
  Enabled: false
Style/InlineComment:
  Enabled: false
Style/MethodCalledOnDoEndBlock:
  Enabled: false
Style/MissingElse:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/OptionHash:
  Enabled: false
Style/TopLevelMethodDefinition:
  Enabled: false
Style/YodaExpression:
  Enabled: false
Style/HashSyntax:
  EnforcedShorthandSyntax: never
