extends: relaxed
rules:
  trailing-spaces: disable
  line-length: disable
ignore: |
  node_modules/
  vendor/
  .build/
  Pods/
  Carthage/
  DerivedData/
  venv/
  .venv/
  .bundle/
  .gradle/
  .m2/
  dist/
  build/
  target/
  .npm/
  .yarn/
  .pnpm/
  tmp/
  var/
